name: Semgrep

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
    paths-ignore:
      - ".github/workflows/**"
  schedule:
    - cron: "36 3 * * *" # random time to avoid spike

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write   # allow posting results to PR
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci

